core/urls.py
from django.contrib import admin
from django.urls import path, include
from weather import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls'))
]

weather/urls.py
from django.urls import path
from . import views

app_name = 'weather'

urlpatterns = [
    path('logout/', views.logout_user, name='logout'),
    path('login/', views.login_user, name='login_user'),
    path('cadastrar/', views.cadastro, name='cadastro'),
    path('pesquisar/clima/', views.clima, name='clima'),
    path('pesquisar/', views.pesquisar, name='pesquisar'),
    path('', views.base_page, name='base-page'),
]

weather/models.py
from django.db import models

# Create your models here.

weather/views/weather_views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

import geocoder
from utils.openweathermap_api import buscar_cidade, verificar_clima, API_KEY

# Create your views here.

# ============================================================================================= #

def cadastro(request):
    if request.method == "GET":
        return render(request, 'main_templates/cadastro.html')
    else:
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        if User.objects.filter(username=username).exists():
            return HttpResponse('Já existe um usuário com esse nome!')
        
        if User.objects.filter(email=email).exists():
            return HttpResponse('Já existe um usuário com esse e-mail!')

        User.objects.create_user(username=username, email=email, password=password)

        return redirect('weather:login_user')
    
def login_user(request):
    if request.method == 'GET':
        return render(request, 'main_templates/login.html')
    else:
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('weather:pesquisar')
        else:
            return render(request, 'main_templates/login.html')

def logout_user(request):
    logout(request)
    return redirect('weather:base-page')

def base_page(request):
    return render(request, 'partials/base.html')


@login_required(login_url='/login/')
def pesquisar(request):
    return render(request, 'main_templates/index.html')

@login_required(login_url='/login/')
def clima(request):
    cidade = request.GET.get('cidade')
    latitude = longitude = None

    LOCALIZACAO = geocoder.ip('me')
    LOCALIZACAO_PAIS = LOCALIZACAO.country

    if cidade:
        latitude, longitude = buscar_cidade(cidade, API_KEY, COUNTRY_CODE=LOCALIZACAO_PAIS)
        dados = verificar_clima(latitude, longitude, API_KEY)
    else:
        dados = None

    if dados:
        dados_do_clima = {
            'cidade': cidade.strip().title(),
            'coords': dados.get('coords'),
            'weather': dados.get('weather')[0] if dados.get('weather') else {},
            'main': dados.get('main'),
            'wind': dados.get('wind'),
        }
    else:
        dados_do_clima = {}

    return render(request,
                'main_templates/clima.html',
                dados_do_clima,
                )

global/templates/main_templates/cadastro.html
{% extends "partials/base.html" %}

{% block title %}Cadastro{% endblock title %}

{% block header %}
<header id="heading">
    <h1 class="h1"><a href="{% url "weather:base-page" %}">WEATHER</a></h1>
    <nav class="links">
            <ul>
                <li><a href="{% url "weather:login_user" %}">LOGIN</a></li>
            </ul>
        </nav>
</header>
{% endblock header %}
{% block content %}
<div id="register-div">
    <h1>CADASTRO</h1>
    <form id="cadastro" action="{% url "weather:cadastro" %}" method="POST">
        {% csrf_token %}
        <input type="text" placeholder="Usuario..." name="username">
        <br>
        <br>
        <input type="text" placeholder="E-mail..." name="email">
        <br>
        <br>
        <input type="text" placeholder="Senha..." name="password">
        <br>
        <br>
        <button type="submit">CADASTRAR</button>
    </form>
</div>
{% endblock content %}

global/templates/main_templates/clima.html
{% extends "partials/base.html" %}
{% block title %}clima de {{ cidade }}{% endblock title %}

{% block content %}
{% load static %}
<div class="result">
    <h1> {{ cidade }} </h1>
    <table class="clima-table">
        <thead class="table-head">
            <tr class="table-column">
                    <th class="table-header">Temperatura</th>
                    <th class="table-header">Umidade</th>
                    <th class="table-header">Sençação Térmica</th>
                    <th class="table-header">Descrição do clima</th>
                </tr>
        </thead>
        <tbody class="table-body">
            <tr class="table-column">
                <td class="table-td"><img class="img-td" src="{% static 'images/Icones_para_clima_do_site/icons8-dia-parcialmente-nublado-100.png' %}">{{ main.temp }}</td>
                <td class="table-td">{{ main.humidity }}%</td>
                <td class="table-td">{{ main.feels_like }}</td>
                {% if weather.description %}
                <td class="table-td">{{ weather.description }}</td>
                {% else %}
                <td class="table-td">Sem descrição</td>
                {% endif %}
            </tr>
        </tbody>
    </table>
    <form class="search-form" action="{% url "weather:clima" %}" method="GET">
        <input class="search-input" type="text" name="cidade" placeholder="Digite o nome da cidade" required>
        <button class="search-button" type="submit">Buscar</button>
    </form>
</div>
{% endblock content %}

global/templates/main_templates/index.html
{% extends "partials/base.html" %}

{% block content %}
    <div class="search-div">
        <h1>DIGITE O NOME DA CIDADE</h1>
        <form class="search-form" method="GET" action="{% url 'weather:clima' %}">
            <input class="search-input" type="text" name="cidade" placeholder="Digite o nome da cidade" required>
            <button class="search-button" type="submit">Buscar</button>
        </form>
    </div>
{% endblock content %}

global/templates/main_templates/login.html
{% extends "partials/base.html" %}

{% block title %}Cadastro{% endblock title %}

{% block header %}
<header id="heading">
    <h1 class="h1"><a href="{% url "weather:base-page" %}">WEATHER</a></h1>
    <nav class="links">
            <ul>
                <li><a href="{% url "weather:cadastro" %}">CADASTRAR-SE</a></li>
            </ul>
        </nav>
</header>
{% endblock header %}
{% block content %}
<div id="register-div">
    <h1>LOGIN</h1>
    <form id="cadastro" action="{% url "weather:login_user" %}" method="POST">
        {% csrf_token %}
        <input type="text" placeholder="Usuario..." name="username">
        <br>
        <br>
        <input type="text" placeholder="Senha..." name="password">
        <br>
        <br>
        <button type="submit">LOGIN</button>
    </form>
</div>
{% endblock content %}

global/templates/partials/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WEATHER</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block header %}
<header id="heading">
    <h1 class="h1">
        {% if user.is_authenticated %}
        <a href="{% url "weather:pesquisar" %}">WEATHER</a>
        {% else %}
        <a href="{% url "weather:base-page" %}">WEATHER</a>
        {% endif %}
    </h1>
    <nav class="links">
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <a href="{% url "weather:logout" %}">SAIR</a>
                </li>
                {% else %}
                <li><a href="{% url "weather:login_user" %}">LOGIN</a></li>
                <li><a href="{% url 'weather:cadastro' %}">CADASTRAR-SE</a></li>
                {% endif %}
            </ul>
        </nav>
</header>
{% endblock header %}
{% block content %}
<div id="base-page">
    <h1>WEATHER</h1>
</div>
{% endblock content %}
</body>
</html>